export const ALL_CLANS = [
  'Arcane Syndicate',
  'Bad Time Barbiezz',
  'Black Sun',
  'Digital Dagger',
  'Digital Geisha',
  'Doonks',
  'Echo Nexus',
  'Ether Mages',
  'Hotep Nation',
  'Quantum Guild',
  'Red Eclipse',
  'Rifters',
  'Skyward Fleet',
  'Starlight Collective',
  'Triad of the Rising Serpent',
  'Vortex Syndicate',
] as const;

export type Clan = (typeof ALL_CLANS)[number];

export const CLAN_FOLDER_MAP: Record<string, string> = {
  'Arcane Syndicate': 'arcane-syndicate',
  'Bad Time Barbiezz': 'bad-time-barbiezz',
  'Black Sun': 'black-sun',
  'Digital Dagger': 'digital-dagger',
  'Digital Geisha': 'digital-geisha',
  'Doonks': 'doonks',
  'Echo Nexus': 'echo-nexus',
  'Ether Mages': 'ether-mages',
  'Hotep Nation': 'hotep-nation',
  'Quantum Guild': 'quantum-guild',
  'Red Eclipse': 'red-eclipse',
  'Rifters': 'rifters',
  'Skyward Fleet': 'skyward-fleet',
  'Starlight Collective': 'starlight-collective',
  'Triad of the Rising Serpent': 'triad-of-the-rising-serpent',
  'Vortex Syndicate': 'vortex-syndicate',
};

export const CLAN_COLORS: Record<string, string> = {
  'Arcane Syndicate': '#9b59b6',
  'Bad Time Barbiezz': '#ff69b4',
  'Black Sun': '#1a1a2e',
  'Digital Dagger': '#00e5ff',
  'Digital Geisha': '#ff6b9d',
  'Doonks': '#f39c12',
  'Echo Nexus': '#2ecc71',
  'Ether Mages': '#8e44ad',
  'Hotep Nation': '#fbbf24',
  'Quantum Guild': '#3498db',
  'Red Eclipse': '#e74c3c',
  'Rifters': '#00e5ff',
  'Skyward Fleet': '#5dade2',
  'Starlight Collective': '#f1c40f',
  'Triad of the Rising Serpent': '#27ae60',
  'Vortex Syndicate': '#e67e22',
};

export const CLAN_TAGLINES: Record<string, string> = {
  'Arcane Syndicate': 'Masters of forbidden tech-magic fusion',
  'Bad Time Barbiezz': 'Chaos incarnate — unpredictable and lethal',
  'Black Sun': 'Shadows that consume all light',
  'Digital Dagger': 'Precision strikes from the digital void',
  'Digital Geisha': 'Elegance weaponized, beauty as battlefield',
  'Doonks': 'Brute force meets unstoppable momentum',
  'Echo Nexus': 'Networked intelligence, distributed power',
  'Ether Mages': 'Reality benders wielding raw ether',
  'Hotep Nation': 'Ancient wisdom forged in cyber-gold',
  'Quantum Guild': 'Probability manipulators, masters of chance',
  'Red Eclipse': 'Revolution written in fire and blood',
  'Rifters': 'Wasteland survivors, rift-born warriors',
  'Skyward Fleet': 'Aerial dominance from the clouds above',
  'Starlight Collective': 'Cosmic harmony channeled through unity',
  'Triad of the Rising Serpent': 'Ancient order, coiled to strike',
  'Vortex Syndicate': 'Chaos engineers riding the storm',
};
